server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # 파일 업로드 용향 제한을 50MB로 상향 (기본값은 1MB)
    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ /index.html;
    }
}