server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # 파일 업로드 용량 제한을 50MB로 상향 (기본값은 1MB)
    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # API 요청을 백앤드로 전달 ( 로컬의 vite proxy 역활)
    location /api {
        proxy_pass http://175.197.69.42;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # API 경로에 대해서도 명시적으로 용량 제한 설정
            client_max_body_size 50M;
    }
}